# Generated by Django 2.0.3 on 2020-04-05 00:24

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Kategori')),
                ('position', models.CharField(max_length=50, verbose_name='Pozisyon')),
                ('name', models.CharField(max_length=50, verbose_name='İsim')),
                ('age', models.CharField(max_length=50, verbose_name='Yaş')),
                ('size', models.CharField(max_length=50, verbose_name='Boy')),
                ('weight', models.CharField(max_length=50, verbose_name='Kilo')),
                ('foot', models.CharField(max_length=50, verbose_name='Kullandığı Ayak')),
                ('club_history', models.CharField(max_length=50, verbose_name='Kulübe Katılma Tarihi')),
                ('hoca_gorüsü', models.TextField()),
                ('player_image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf Ekleyin')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'ordering': ['-age'],
            },
        ),
        migrations.CreateModel(
            name='Duyuru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duyuru_category', models.CharField(max_length=50, verbose_name='Kategori')),
                ('duyuru_title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('duyuru_content', ckeditor.fields.RichTextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galeri_category', models.CharField(max_length=50, verbose_name='Kategori')),
                ('galeri_title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('galeri_content', models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf veya Video Ekleyin')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
        migrations.CreateModel(
            name='Haber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haber_category', models.CharField(max_length=50, verbose_name='Kategori')),
                ('haber_title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('haber_image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf veya Video Ekleyin')),
                ('haber_content', ckeditor.fields.RichTextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
