# Generated by Django 2.0.3 on 2020-04-06 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0002_puan_durumu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('club_content', models.CharField(max_length=50, verbose_name='İçerik')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
